uc-cdis/sower-jobs

manifest_indexing/indexd_manifest_job.py, manifest_indexing/manifest_indexing.Dockerfile, manifest_indexing/manifest_indexing_job.py, manifest_indexing/utils.py
=> chore(refactor): refactor

manifest_indexing/indexd_manifest_job.Dockerfile, manifest_indexing/manifest_indexing.Dockerfile
=> fix(docker): install gen3 with pip

NOTICE
=> feat(NOTICE): add NOTICE

README.md
- docs reflect naming convention from Gen3 automation
=> chore(docs): update readme to reflect naming convention for SAs

manifest_indexing/manifest_indexing_job.py
- use correct var for creds in indexing jobs
=> fix(indexing): use correct var for creds

manifest_indexing/indexd_manifest_job.py
=> fix(env): fix env

manifest_indexing/indexd_manifest_job.Dockerfile, metadata_ingestion/metadata_ingestion.Dockerfile
Improving manifest indexing feature.
=> chore(qa): Pinning Gen3 2.3.2 to fix byte order mark

manifest_indexing/indexd_manifest_job.Dockerfile, manifest_indexing/manifest_indexing.Dockerfile, metadata_ingestion/get_dbgap_metadata_manifest.Dockerfile, metadata_ingestion/metadata_ingestion.Dockerfile
- fix edge-cases with manifest format by updating sdk
=> fix(bom): updgrade sdk version to fix bugs

manifest_indexing/manifest_indexing.Dockerfile
=> chore(dependencies): use gen3sdk_python:2.4.0

metadata_ingestion/get_dbgap_metadata_manifest.Dockerfile
Need to unblock this ASAP for testing purposes.
=> chore(qa): Short-term mitigation for docker cache and py dependency mgmt

README.md, manifest_merging/manifest_merging.Dockerfile, manifest_merging/manifest_merging_job.py, manifest_merging/settings.py, manifest_merging/utils.py
- Add new sower job to merge bucket manifests using the SDK
=> PXP-6413 Create sower job for bucket manifest merging

.github/labeler.yml, .github/workflows/labeler.yml, Jenkinsfile, Jenkinsfile.security
Adding Jenkinsfile and Jenkinsfile.security to the repo 
also adding labeler yaml
=> adding Jenkinsfile and labeler

manifest_indexing/manifest_indexing.Dockerfile
Jira Ticket: [PXP-8971](https://ctds-planx.atlassian.net/browse/PXP-8971)
New python base image
=> feat(python3.6-buster): update manifest-indexing dockerfile

manifest_merging/manifest_merging.Dockerfile
Jira Ticket: [PXP-8972](https://ctds-planx.atlassian.net/browse/PXP-8972)
New python base image
=> feat(python3.6-buster): update manifest-merging dockerfile

metadata_ingestion/metadata_ingestion.Dockerfile
Jira Ticket: [PXP-8947](https://ctds-planx.atlassian.net/browse/PXP-8947)
New python base image
=> feat(python3.6-buster): update metadata_ingestion dockerfile

metadata_ingestion/get_dbgap_metadata_manifest.Dockerfile
Jira Ticket: [PXP-8961](https://ctds-planx.atlassian.net/browse/PXP-8961)
New python base image
=> feat(python3.6-buster): update get_dbgap_metadata dockerfile

manifest_indexing/manifest_indexing.Dockerfile, manifest_merging/manifest_merging.Dockerfile, metadata_ingestion/get_dbgap_metadata_manifest.Dockerfile, metadata_ingestion/metadata_ingestion.Dockerfile
- update to latest base image to avoid issue with dockerrun
=> fix(docker): update to latest base image to avoid issue with dockerrun

.github/workflows/image_build_push.yaml, Jenkinsfile.security, README.md, delete_expired_objects/delete_expired_objects_job.py, metadata_delete_expired_objects/README.md, metadata_delete_expired_objects/metadata_delete_expired_objects.Dockerfile, metadata_delete_expired_objects/metadata_delete_expired_objects_job.py
Jira Ticket: [PXP-9985](https://ctds-planx.atlassian.net/browse/PXP-9985)
updates https://github.com/uc-cdis/sower-jobs/pull/39
Requires https://github.com/uc-cdis/gen3sdk-python/pull/167
=> PXP-9985 Use client credentials instead of API key

.gitignore, export_job/export_zip_from_manifest_job.py
Need to use with https://github.com/uc-cdis/metadata-service/pull/90
- update batch export job for MDS v3 AggMDS response syntax
=> fix: update for mds 3.0.0

export_job/export_zip_from_manifest_job.py
Jira Ticket: [HP-1261](https://ctds-planx.atlassian.net/browse/HP-1261)
- batch export job now can accept a manifest from input data
[HP-1261]: https://ctds-planx.atlassian.net/browse/HP-1261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> HP-1261 feat batch export input manifest

export_job/export_zip_from_manifest_job.py
Link to JIRA ticket if there is one: https://ctds-planx.atlassian.net/browse/HP-1955
- Use V4 signature for batch-export job presigned URLs
=> fix use v4 url for batch-export
